### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by pablocrivella** [go-openapi/spec3#6]
I was wondering how could I try to contribute to this project.

**Comment by casualjim** [comment]
You can just send PR's 
We have a slack org but we're also around in the gophers slack.

**Comment by pablocrivella** [comment]
oh okay! I was asking if there were any low hanging fruit issues I could try to solve, maybe documentation missing, tests, etc, I see there is a checklist on the README but I'm not sure how updated it is.

**Comment by casualjim** [comment]
Ah that checklist in the readme was added in the last few commits, so it's up to date
